version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: monstera-money-postgres
    environment:
      POSTGRES_DB: monstera_money
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: monstera-money-telegram-api
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    ports:
      - "8081:8081"
    volumes:
      - telegram_data:/var/lib/telegram-bot-api
    restart: unless-stopped

volumes:
  postgres_data:
  telegram_data: